server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/g-sneaker?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
api:
  prefix: api/v1