server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://dpg-clocl83j65ls73f71nl0-a.singapore-postgres.render.com/g_sneaker_ttu0
    username: truongnq
    password: XRdKUh6Yj8C25Z5yR263o9xMAKlIrNTA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
api:
  prefix: api/v1